# Generated by Django 4.2.3 on 2023-07-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student_age'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
